require:
  - rubocop-rspec
  - rubocop-performance
AllCops:
  TargetRubyVersion: 3.0
  NewCops: disable
  SuggestExtensions: false
Metrics/BlockLength:
  Max: 100
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
RSpec/MultipleExpectations:
  Max: 10
