require:
  - rubocop-rake
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.7
  NewCops: disable
Metrics/BlockLength:
  Max: 100
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
RSpec/MultipleExpectations:
  Max: 10