name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '34 22 2 * *'

jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # https://www.ruby-lang.org/en/downloads/branches/
        ruby: ["2.7", "3.0", "3.1", "3.2", "3.3"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake spec
